/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#2b3040",
        "tertiary": "#ecd4ff",
        "on-error": "#690005",
        "outline": "#859399",
        "secondary-fixed": "#ffdad7",
        "on-tertiary": "#4a0080",
        "on-background": "#dee1f7",
        "on-error-container": "#ffdad6",
        "primary": "#a5e7ff",
        "surface-dim": "#0e1322",
        "on-primary-fixed-variant": "#004e60",
        "tertiary-fixed": "#f0dbff",
        "on-secondary-fixed-variant": "#910818",
        "surface-tint": "#47d6ff",
        "on-secondary": "#68000c",
        "surface-bright": "#343949",
        "background": "#05070A",
        "surface-container-lowest": "#090e1c",
        "outline-variant": "#3c494e",
        "secondary-container": "#910818",
        "on-tertiary-fixed-variant": "#6900b3",
        "secondary-fixed-dim": "#ffb3ae",
        "surface-variant": "#2f3445",
        "inverse-surface": "#dee1f7",
        "primary-container": "#00d2ff",
        "surface-container-high": "#25293a",
        "error": "#ffb4ab",
        "surface-container": "#1a1f2f",
        "primary-fixed-dim": "#47d6ff",
        "on-surface": "#dee1f7",
        "on-tertiary-container": "#7400c5",
        "surface": "#0e1322",
        "on-primary-container": "#00566a",
        "on-secondary-fixed": "#410005",
        "on-secondary-container": "#ff9993",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#ddb7ff",
        "inverse-primary": "#00677f",
        "primary-fixed": "#b6ebff",
        "on-primary-fixed": "#001f28",
        "on-tertiary-fixed": "#2c0050",
        "secondary": "#ffb3ae",
        "surface-container-highest": "#2f3445",
        "on-surface-variant": "#bbc9cf",
        "on-primary": "#003543",
        "tertiary-container": "#dab0ff",
        "surface-container-low": "#161b2b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-margin": "clamp(1rem, 5vw, 40px)",
        "gutter": "24px",
        "component-padding-x": "24px",
        "component-padding-y": "12px",
        "section-gap": "clamp(60px, 10vw, 120px)"
      },
      fontFamily: {
        "display-lg": ["Syne"],
        "headline-md": ["Syne"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["Syne"],
        "body-lg": ["Hanken Grotesk"],
        "label-lg": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "display-md": ["Syne"],
        "body-sm": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Syne"],
        "body": ["Hanken Grotesk"],
        "display": ["Syne"]
      },
      fontSize: {
        "display-lg": ["72px", {"lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg": ["40px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "1.5", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.5", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "display-md": ["56px", {"lineHeight": "1.3", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "1.3", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
